### ISSUE TITLE
Cloud: If MRO when completed = QUOTE then skip Review Quote against MRO Status

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#128]
Cloud: If MRO when completed = QUOTE then skip Review Quote against MRO Status

giovani to elaborate

**Comment by giovanicani** [comment]
When MRO is completed and labour lines and part lines and hours and quantity are the same as QUOTE, then auto-flag box below:

![image](https://cloud.githubusercontent.com/assets/5666297/12830952/f1930220-cb5f-11e5-8b7b-c0627d8039f2.png)

So that is ready for billing. On the audit log enter a line: 
Quote matches MRO, Quote has been auto-set Ready for Bill as per Quote. User should be SYSTEM.

**Comment by giovanicani** [comment]
Team, please work on this one, any question let me know.

**Comment by d3ssupport** [comment]
Work in Progress!

**Comment by tufailzafar** [comment]
still work in progress

**Comment by d3sqa** [comment]
@giovanicani, we are going to stop the RO from sending to EMDECS i.e. after RO completion from mobile the RO will land into COMPLETE status rather than EMDECS OK.
This has been done because if there is a mismatch occurred, the RO will be sent to EMDECS and the user will not be able to correct the data. Are you OK with it ?

Also, currently we are comparing QUOTE ESTIMATE HRS to MOBILE HRS and not to QUOTE HRS as they will never match. Please give your feedback ?

![122222](https://cloud.githubusercontent.com/assets/13255706/13135312/47adf49a-d631-11e5-8405-cd227c481e5c.png)

**Comment by giovanicani** [comment]
No. 

Please send into EMDECS even when mismatch. 

Quote will be adjusted by user NOT MRO. 

Nothing should change on the MRO side. 

Comparison is correct: quote estimate hours against mobile actual hours. 

--
Giovani Cani

**Comment by giovanicani** [comment]
I would like to test this tomorrow. please make sure that this change is completed. Thanks.

**Comment by d3sqa** [comment]
@giovanicani, The comparison has been done between RO and Quote  on following parameters:

1. # of Labour Lines
2. Labour Hours
3. Labour description
4. # of Parts
5. Parts QTY

However, we are facing some issues when there are multiple labour lines and one of a labour hrs field is changed of some middle labour line, then the check is by passed and the Quote's status changes to 'BILL AS PER QUOTE PENDING'.
Also, when a particular labour line is deleted from RO, the check is by passed and the quote's status is changed to 'BILL AS PER QUOTE PENDING'.

We need some time to fix these two issues. We would suggest not to roll out this change in the upcoming release (if it is scheduled on 22nd February) because more time on implementation and end to end testing of workflow and comparison needs to be done to avoid the impact on other feature. Need your feedback on this

**Comment by giovanicani** [comment]
Okay. Agreed. 

Take your time to fix the issues and make a note with questions. We will have a meeting on Monday morning to discuss. After that we will come up with a revised released date. 

Thanks. 

--
Giovani Cani

**Comment by giovanicani** [comment]
@tufailzafar can I test this ?

**Comment by d3sqa** [comment]
@giovanicani, yes you can test it (UAT) with an exception of the above written points as they are not done yet.

**Comment by giovanicani** [comment]
Ok. Thanks

--
Giovani Cani

**Comment by giovanicani** [comment]
FYI... I have setup a meeting tomorrow at 7:30AM to discuss. 

I also cancelled all other recurring meetings on the quote system

**Comment by giovanicani** [comment]
it seems to be working well based on my tests... please only do the following:

Add on the audit log something like this:

"Quote updated to bill as per quote status as all MRO Labour(s) / Part(s) match the approved quote."

or

"Quote updated to review pending status as MRO Labour(s) / Part(s) do not match the approved quote."

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Below issues are fixed now:

1. When there are multiple labour lines and one of a labour hrs field is changed of some middle labour line, then the check is by passed and the Quote's status changes to 'BILL AS PER QUOTE PENDING'.

2. When a particular labour line is deleted from RO, the check is by passed and the quote's status is changed to 'BILL AS PER QUOTE PENDING'.

The activity is logged at audit log as well.

Ready to test in UAT Environment

**Comment by giovanicani** [comment]
Based on test with the team... when labour has no part on quote, however a part is added on MRO status is being sent to BILL AS PER QUOTE PENDING, which is incorrect.

Any difference between quote and mro should flag the quote to review pending.

Quote and MRO numbers as per below:

![image](https://cloud.githubusercontent.com/assets/5666297/13218828/0d54bfca-d93a-11e5-898c-0e22bc1f8682.png)

**Comment by d3ssupport** [comment]
Done in UAT. Ready for Testing.

**Comment by giovanicani** [comment]
original issue resolved when quote has only one MRO.

Issue re-occurs when quote has multiple MROs, see Q000576... part added on the second MRO.

**Every time all labour and all parts (part id and quantity, labour id and number of hours) from all the MROs generated from the quote, are different from the quote parts and labour, please set to REVIEW AGAINST QUOTE PENDING**


Another issue, after closed was checked...
![image](https://cloud.githubusercontent.com/assets/5666297/13228571/b8e137c6-d96a-11e5-9a62-6a30adab6218.png)

**Comment by d3sqa** [comment]
Issues which occurred during multiple ROs are now resolved and ready to test in UAT.

Also, we are unable to replicate the CLOSE status issue as per the above written steps. The Quote goes to CLOSE status when Close checkbox is checked and Saved. Can you please let us know the detailed steps if it is replicated at your end ?

**Comment by giovanicani** [comment]
testing this right now...

**Comment by giovanicani** [comment]
[2016-02-23, 8:02:21 AM] Giovani Cani: still not working, but look at the quote and the 2 MROs...

[2016-02-23, 8:03:07 AM] Giovani Cani: they are different, but the system still bypassed the REVIEW stage...
[2016-02-23, 8:03:35 AM] Giovani Cani: any difference between MRO and QUOTEs need to be sent for REVIEW... not sure how can I explain this more clearly.
[2016-02-23, 8:04:55 AM] Giovani Cani: its like you quote a customer for a laptop... but then sell him a entire rack of servers.... you cannot charge him the laptop, you need to charge the rack of servers.
[2016-02-23, 8:05:27 AM] Giovani Cani: right now, the way the program is... you are charging him the laptop even though he got all the servers which were 10x more expensive

![screen shot 2016-02-23 at 8 02 09 am](https://cloud.githubusercontent.com/assets/5666297/13252364/4394ed74-da04-11e5-8cc7-80dda1587dc5.png)

**Comment by d3ssupport** [comment]
As per earlier requirement in the github ticket..we were just comparing parts QTY and num of parts
We didnt catered Par_id.

Now we have done it as well...kindly check and let us know

**Comment by giovanicani** [comment]
Please see image below, wondering why this didn't go straight to **Bill as per Quote Pending**, is it because of the &amp ?

![image](https://cloud.githubusercontent.com/assets/5666297/13409218/f3797d04-deff-11e5-9ae0-ee8bde799411.png)

**Comment by d3sqa** [comment]
Ready to test in UAT Environment

**Comment by giovanicani** [comment]
Working. Ready to be released.
