### ISSUE TITLE
Cloud: Quote Listing Filters & Default Values

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#34]
By default users should only see records for their Location (Branch)

Add the following filters,

Quote #
Unit #
Preferred #
Customer
Date Range
Reference #

**Comment by d3sqa** [comment]
Records based on user location are displayed now. The filter has also been implemented with following  search parameters:

Quote #
Unit #
Preferred #
Customer
Date Range
Reference #

Done at Development environment. It will be available in the next release at UAT

**Comment by giovanicani** [comment]
filter does NOT work at ALL! Fields are there, however doesn't filter properly. Entered bogus info for customer, preferred number, quote number and still see records

![image](https://cloud.githubusercontent.com/assets/5666297/12012496/c42b90a8-acc5-11e5-97b5-29d8ec9ac212.png)

**Comment by d3sqa** [comment]
Fixed. Done at Development Environment. It will be available in the next release at UAT.

**Comment by giovanicani** [comment]
Filtering seems to work now... please make customer a drop down list. thanks.

**Comment by d3sqa** [comment]
Done at Development Environment. It will be available in the next release at UAT.

**Comment by giovanicani** [comment]
NOT OK!

Search needs to be similar to the search inside of the quote, where user can type in values (searchable code and description should be visible and searchable)

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Done at Development Environment. It will be available in the next release at UAT.

**Comment by giovanicani** [comment]
works.
