### ISSUE TITLE
Cloud: If default location not set, show all records on Quote

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#84]
If Default Location for user is not set, then show all records.

Also popup message:
![image](https://cloud.githubusercontent.com/assets/5666297/12555404/16d70acc-c34f-11e5-8baf-70a13d48cb93.png)

**Comment by giovanicani** [comment]
work in progress as per DEV team.

**Comment by d3ssupport** [comment]
Done. Ready to test in UAT.

![image](https://cloud.githubusercontent.com/assets/13255682/12613433/817718e0-c51b-11e5-945a-6d373c9b691f.png)

**Comment by giovanicani** [comment]
Are you sure this is working ? User has a loc_id_default, but I still get the message.

![image](https://cloud.githubusercontent.com/assets/5666297/12614505/64428f7c-c4ce-11e5-881c-c290753a55b8.png)

**Comment by giovanicani** [comment]
working
